language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/npm"

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

sudo: false

before_install:
  - npm config set loglevel warn

install: npm ci

before_script:
  - git config --global user.email team+camperbot@freeCodeCamp.org
  - git config --global user.name "CamperBot"

jobs:
  include:
    - stage: lint
      script: npm-run-all -p lint test:guide-directories
      install: npm ci --ignore-scripts
    - stage: test
      script: npm-run-all -p test:client test:server
    - stage: test-curriculum
      script: npm run test:curriculum
      env: LOCALE=english
    - stage: test-curriculum
      script: npm run test:curriculum
      env: LOCALE=arabic
